@echo off
setlocal EnableExtensions EnableDelayedExpansion
title Final Android Rebuild

pushd "%~dp0" >nul 2>nul
if errorlevel 1 (
    echo ERROR: Unable to open script directory: %~dp0
    goto :end
)

set "ROOT_DIR=%CD%"
set "ANDROID_DIR=%ROOT_DIR%\hmdm-android"
set "VERSION_FILE=%ANDROID_DIR%\version.properties"
set "ENV_FILE=%ROOT_DIR%\.env.android"
set "APP_ARTIFACT_DIR=%ROOT_DIR%\app"
set "APP_INSTALLER_DIR=%ROOT_DIR%\app-installer"

set "BUILD_TYPE=production"
set "ANDROID_STAGE_BASE_URL=https://brother-pharmach-mdm-stage.space"
set "ANDROID_PROD_BASE_URL=https://brothers-mdm.com"

echo Building Android enterprise APK/AAB and refreshing local artifacts only...
echo This will NOT update database and will NOT touch hmdm-postgres.
echo.

if not exist "%ANDROID_DIR%\gradlew.bat" (
    echo ERROR: Missing %ANDROID_DIR%\gradlew.bat
    goto :fail
)

if not exist "%VERSION_FILE%" (
    echo ERROR: Missing %VERSION_FILE%
    goto :fail
)

if not exist "%ENV_FILE%" (
    echo WARNING: .env.android not found. Using production defaults.
) else (
    for /f "usebackq tokens=1,* delims==" %%A in (`findstr /B /I "BUILD_TYPE= ANDROID_STAGE_BASE_URL= ANDROID_PROD_BASE_URL=" "%ENV_FILE%"`) do (
        if /I "%%A"=="BUILD_TYPE" set "BUILD_TYPE=%%B"
        if /I "%%A"=="ANDROID_STAGE_BASE_URL" set "ANDROID_STAGE_BASE_URL=%%B"
        if /I "%%A"=="ANDROID_PROD_BASE_URL" set "ANDROID_PROD_BASE_URL=%%B"
    )
)

for /f "tokens=* delims= " %%A in ("!BUILD_TYPE!") do set "BUILD_TYPE=%%A"
for %%A in ("!BUILD_TYPE!") do set "BUILD_TYPE=%%~A"
if /I "!BUILD_TYPE!"=="prod" set "BUILD_TYPE=production"

if /I "!BUILD_TYPE!"=="stage" (
    set "ANDROID_BASE_URL=!ANDROID_STAGE_BASE_URL!"
) else if /I "!BUILD_TYPE!"=="production" (
    set "ANDROID_BASE_URL=!ANDROID_PROD_BASE_URL!"
) else (
    echo ERROR: Invalid BUILD_TYPE in .env.android. Use stage or production.
    goto :fail
)

set "ANDROID_SECONDARY_BASE_URL=!ANDROID_BASE_URL!"

set "SDK_DIR="
if defined ANDROID_HOME if exist "%ANDROID_HOME%\platform-tools" set "SDK_DIR=%ANDROID_HOME%"
if not defined SDK_DIR if defined ANDROID_SDK_ROOT if exist "%ANDROID_SDK_ROOT%\platform-tools" set "SDK_DIR=%ANDROID_SDK_ROOT%"
if not defined SDK_DIR if exist "%LOCALAPPDATA%\Android\Sdk\platform-tools" set "SDK_DIR=%LOCALAPPDATA%\Android\Sdk"
if not defined SDK_DIR if exist "%USERPROFILE%\AppData\Local\Android\Sdk\platform-tools" set "SDK_DIR=%USERPROFILE%\AppData\Local\Android\Sdk"

if not defined SDK_DIR if exist "%ANDROID_DIR%\local.properties" (
    for /f "tokens=1,* delims==" %%A in ('findstr /B /I "sdk.dir=" "%ANDROID_DIR%\local.properties"') do set "RAW_SDK=%%B"
    if defined RAW_SDK (
        set "RAW_SDK=!RAW_SDK:\\=\!"
        set "RAW_SDK=!RAW_SDK:\:=:!"
        if exist "!RAW_SDK!\platform-tools" set "SDK_DIR=!RAW_SDK!"
    )
)

if not defined SDK_DIR (
    echo ERROR: Android SDK not found.
    echo Set ANDROID_HOME or install Android SDK in %LOCALAPPDATA%\Android\Sdk
    goto :fail
)

set "ANDROID_HOME=%SDK_DIR%"
set "ANDROID_SDK_ROOT=%SDK_DIR%"
set "SDK_ESC=%SDK_DIR:\=\\%"
(
    echo # Auto-generated by final-rebuild-android-only.bat
    echo sdk.dir=!SDK_ESC!
) > "%ANDROID_DIR%\local.properties"

echo Android BUILD_TYPE: !BUILD_TYPE!
echo Android BASE_URL: !ANDROID_BASE_URL!
echo Android SECONDARY_BASE_URL: !ANDROID_SECONDARY_BASE_URL!
echo Using Android SDK: !SDK_DIR!
echo.

where powershell >nul 2>nul
if errorlevel 1 (
    echo ERROR: Windows PowerShell is required but not found.
    goto :fail
)

for /f "usebackq delims=" %%V in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "$p='%VERSION_FILE%'; $kv=@{}; Get-Content $p ^| ForEach-Object { if ($_ -match '^(VERSION_CODE^|VERSION_NAME)=(.*)$') { $kv[$matches[1]]=$matches[2].Trim() } }; if (-not $kv.ContainsKey('VERSION_CODE') -or -not $kv.ContainsKey('VERSION_NAME')) { exit 2 }; $code=[int]$kv['VERSION_CODE']+1; $n=$kv['VERSION_NAME'].Split('.'); $maj=[int]$n[0]; $min=0; if ($n.Length -gt 1) { $min=[int]$n[1] }; $min++; if ($min -ge 100) { $maj++; $min=0 }; $newName=('{0}.{1}' -f $maj,$min); @('# Auto-managed by final-rebuild-android-only.bat -- do not edit manually','# VERSION_CODE must increase monotonically for each Play Console upload',('VERSION_CODE=' + $code),('VERSION_NAME=' + $newName)) ^| Set-Content -Encoding Ascii $p; Write-Output ($code.ToString() + '^|' + $newName)"`) do set "VER_OUT=%%V"

if not defined VER_OUT (
    echo ERROR: Failed to update version.properties.
    goto :fail
)

for /f "tokens=1,2 delims=|" %%A in ("!VER_OUT!") do (
    set "VERSION_CODE=%%A"
    set "VERSION_NAME=%%B"
)
echo Android version bumped: code=!VERSION_CODE!, name=!VERSION_NAME!

pushd "%ANDROID_DIR%"
call gradlew.bat -PmdmBaseUrl="!ANDROID_BASE_URL!" -PmdmSecondaryBaseUrl="!ANDROID_SECONDARY_BASE_URL!" bundleEnterpriseRelease assembleEnterpriseRelease --no-daemon
if errorlevel 1 (
    popd
    echo ERROR: Android build failed.
    goto :fail
)
popd

set "APK_PATH=%ANDROID_DIR%\app\build\outputs\apk\enterprise\release\app-enterprise-release.apk"
set "AAB_PATH=%ANDROID_DIR%\app\build\outputs\bundle\enterpriseRelease\app-enterprise-release.aab"

if not exist "%APK_PATH%" (
    echo ERROR: APK not found at %APK_PATH%
    goto :fail
)

if not exist "%AAB_PATH%" (
    echo ERROR: AAB not found at %AAB_PATH%
    goto :fail
)

set "APK_NAME=app-enterprise-release-!VERSION_CODE!.apk"
if not exist "%APP_ARTIFACT_DIR%" mkdir "%APP_ARTIFACT_DIR%"
if not exist "%APP_INSTALLER_DIR%" mkdir "%APP_INSTALLER_DIR%"

copy /Y "%APK_PATH%" "%APP_ARTIFACT_DIR%\app-enterprise-release.apk" >nul
copy /Y "%AAB_PATH%" "%APP_ARTIFACT_DIR%\app-enterprise-release.aab" >nul
copy /Y "%APK_PATH%" "%APP_ARTIFACT_DIR%\!APK_NAME!" >nul
copy /Y "%APK_PATH%" "%APP_INSTALLER_DIR%\app-enterprise-release.apk" >nul

echo.
echo Success: Android enterprise APK/AAB built.
echo Refreshed:
echo   - app/app-enterprise-release.apk
echo   - app/app-enterprise-release.aab
echo   - app/!APK_NAME!
echo   - app-installer/app-enterprise-release.apk
echo.
goto :end

:fail
echo.
echo Operation did not complete.
echo.

:end
popd >nul 2>nul
echo Press any key to exit...
pause >nul
endlocal
