#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANDROID_DIR="$ROOT_DIR/hmdm-android"
ENV_FILE="$ROOT_DIR/.env.android"
VERSION_FILE="$ANDROID_DIR/version.properties"
LOCAL_PROPERTIES_FILE="$ANDROID_DIR/local.properties"
APP_INSTALLER_DIR="$ROOT_DIR/app-installer"

cd "$ROOT_DIR"

echo "Building Android enterprise APK/AAB and refreshing local artifacts only..."
echo "This will NOT update database and will NOT touch hmdm-postgres."
echo

if [[ ! -d "$ANDROID_DIR" ]]; then
  echo "ERROR: Android project directory not found: $ANDROID_DIR"
  exit 1
fi

if [[ ! -f "$ANDROID_DIR/gradlew" ]]; then
  echo "ERROR: Missing gradle wrapper: $ANDROID_DIR/gradlew"
  exit 1
fi

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "ERROR: Missing version file: $VERSION_FILE"
  exit 1
fi

BUILD_TYPE="production"
ANDROID_STAGE_BASE_URL="https://brother-pharmach-mdm-stage.space"
ANDROID_PROD_BASE_URL="https://brothers-mdm.com"
ANDROID_BASE_URL=""
ANDROID_SECONDARY_BASE_URL=""

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  . <(tr -d '\r' < "$ENV_FILE")
  set +a
fi

BUILD_TYPE_RAW="${ANDROID_BUILD_TYPE:-${BUILD_TYPE:-production}}"
BUILD_TYPE="$(printf '%s' "$BUILD_TYPE_RAW" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')"
if [[ "$BUILD_TYPE" == "prod" ]]; then
  BUILD_TYPE="production"
fi

ANDROID_STAGE_BASE_URL="${ANDROID_STAGE_BASE_URL:-https://brother-pharmach-mdm-stage.space}"
ANDROID_PROD_BASE_URL="${ANDROID_PROD_BASE_URL:-https://brothers-mdm.com}"

case "$BUILD_TYPE" in
  stage)
    ANDROID_BASE_URL="${ANDROID_BASE_URL:-$ANDROID_STAGE_BASE_URL}"
    ;;
  production)
    ANDROID_BASE_URL="${ANDROID_BASE_URL:-$ANDROID_PROD_BASE_URL}"
    ;;
  *)
    echo "ERROR: Invalid BUILD_TYPE '$BUILD_TYPE_RAW'. Use stage or production."
    exit 1
    ;;
esac

ANDROID_SECONDARY_BASE_URL="${ANDROID_SECONDARY_BASE_URL:-$ANDROID_BASE_URL}"

normalize_windows_path_for_unix() {
  local p="$1"
  if printf '%s' "$p" | grep -Eq '^[A-Za-z]:\\'; then
    local drive
    drive="$(printf '%s' "$p" | cut -c1 | tr '[:upper:]' '[:lower:]')"
    local rest
    rest="$(printf '%s' "$p" | cut -c3- | sed 's#\\#/#g')"
    printf '/mnt/%s/%s' "$drive" "$rest"
    return
  fi
  printf '%s' "$p"
}

resolve_android_sdk_dir() {
  local sdk_from_local=""
  if [[ -f "$LOCAL_PROPERTIES_FILE" ]]; then
    sdk_from_local="$(grep -E '^sdk\.dir=' "$LOCAL_PROPERTIES_FILE" | tail -1 | cut -d= -f2- | tr -d '\r')"
    sdk_from_local="${sdk_from_local//\\:/:}"
    sdk_from_local="$(normalize_windows_path_for_unix "$sdk_from_local")"
  fi

  local candidates=()
  [[ -n "${ANDROID_HOME:-}" ]] && candidates+=("${ANDROID_HOME}")
  [[ -n "${ANDROID_SDK_ROOT:-}" ]] && candidates+=("${ANDROID_SDK_ROOT}")
  [[ -n "$sdk_from_local" ]] && candidates+=("${sdk_from_local}")
  candidates+=(
    "$HOME/Android/Sdk"
    "$HOME/android-sdk"
    "/opt/android-sdk"
  )

  local win_sdk
  for win_sdk in /mnt/c/Users/*/AppData/Local/Android/Sdk /c/Users/*/AppData/Local/Android/Sdk; do
    [[ -d "$win_sdk" ]] && candidates+=("$win_sdk")
  done

  local sdk=""
  local c
  for c in "${candidates[@]}"; do
    [[ -z "$c" ]] && continue
    if [[ -d "$c" && -d "$c/platform-tools" ]]; then
      sdk="$c"
      break
    fi
  done

  if [[ -z "$sdk" ]]; then
    echo "ERROR: Android SDK not found."
    echo "Set ANDROID_HOME/ANDROID_SDK_ROOT or install SDK under ~/Android/Sdk"
    exit 1
  fi

  export ANDROID_HOME="$sdk"
  export ANDROID_SDK_ROOT="$sdk"

  {
    echo "# Auto-generated by final-rebuild-android-only.sh"
    echo "sdk.dir=$sdk"
  } > "$LOCAL_PROPERTIES_FILE"

  echo "Using Android SDK: $sdk"
}

bump_android_version() {
  local cur_code cur_name
  cur_code="$(grep '^VERSION_CODE=' "$VERSION_FILE" | head -1 | cut -d= -f2 | tr -d '[:space:]')"
  cur_name="$(grep '^VERSION_NAME=' "$VERSION_FILE" | head -1 | cut -d= -f2 | tr -d '[:space:]')"

  if [[ -z "$cur_code" || -z "$cur_name" ]]; then
    echo "ERROR: VERSION_CODE or VERSION_NAME missing in $VERSION_FILE"
    exit 1
  fi

  local new_code=$((cur_code + 1))
  local major minor
  major="${cur_name%%.*}"
  minor="${cur_name#*.}"
  minor=$((10#$minor + 1))
  if [[ "$minor" -ge 100 ]]; then
    major=$((major + 1))
    minor=0
  fi
  local new_name="${major}.${minor}"

  {
    echo "# Auto-managed by final-rebuild-android-only.sh -- do not edit manually"
    echo "# VERSION_CODE must increase monotonically for each Play Console upload"
    echo "VERSION_CODE=${new_code}"
    echo "VERSION_NAME=${new_name}"
  } > "${VERSION_FILE}.tmp"
  mv "${VERSION_FILE}.tmp" "$VERSION_FILE"

  echo "Android version bumped: code=${new_code}, name=${new_name}"
}

resolve_android_sdk_dir
bump_android_version

echo "Android BUILD_TYPE: $BUILD_TYPE"
echo "Android BASE_URL: $ANDROID_BASE_URL"
echo "Android SECONDARY_BASE_URL: $ANDROID_SECONDARY_BASE_URL"

chmod +x "$ANDROID_DIR/gradlew"
(
  cd "$ANDROID_DIR"
  ./gradlew -PmdmBaseUrl="$ANDROID_BASE_URL" -PmdmSecondaryBaseUrl="$ANDROID_SECONDARY_BASE_URL" bundleEnterpriseRelease assembleEnterpriseRelease --no-daemon
)

APK_PATH="$ANDROID_DIR/app/build/outputs/apk/enterprise/release/app-enterprise-release.apk"
AAB_PATH="$ANDROID_DIR/app/build/outputs/bundle/enterpriseRelease/app-enterprise-release.aab"

if [[ ! -f "$APK_PATH" ]]; then
  echo "ERROR: APK not found at $APK_PATH"
  exit 1
fi

if [[ ! -f "$AAB_PATH" ]]; then
  echo "ERROR: AAB not found at $AAB_PATH"
  exit 1
fi

mkdir -p "$APP_INSTALLER_DIR"
cp -f "$APK_PATH" "$APP_INSTALLER_DIR/app-enterprise-release.apk"

echo
echo "Success: Android enterprise APK/AAB built."
echo "Refreshed:"
echo "  - app-installer/app-enterprise-release.apk"
echo "WSL Android rebuild completed successfully."
