#!/usr/bin/env python3
"""
Brother Pharmach MDM - One-command web installer.

Usage:
  python3 setup.py

What it does:
  1) Starts a local setup web page and opens it in your browser.
  2) Accepts environment values once and writes hmdm-server/.env.
  3) Runs docker compose build + up -d (with tunnel profile when token exists).
  4) Streams progress/logs in the web page.
  5) Shows "Continue to Admin Panel" when healthy.

Note:
  A plain `docker build` command cannot launch interactive UI by itself because
  image build runs in a non-interactive build context. This script is the
  one-command installer entrypoint for the requested flow.
"""

import html
import json
import os
import secrets
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT_DIR = Path(__file__).parent.resolve()
SERVER_DIR = ROOT_DIR / "hmdm-server"
ENV_FILE = SERVER_DIR / ".env"
SETUP_STATE_FILE = SERVER_DIR / ".setup_completed.json"

HOST = "127.0.0.1"
PORT = 8765

STATE_LOCK = threading.Lock()
STATE = {
    "running": False,
    "done": False,
    "error": "",
    "phase": "idle",
    "logs": [],
    "base_url": "",
    "http_port": "8080",
}


def load_env(path: Path) -> dict:
    env = {}
    if path.exists():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def write_env(path: Path, v: dict):
    lines = [
        "# Brother Pharmach MDM - Environment Configuration",
        "# Generated by setup.py",
        "",
        "# Server",
        f"BASE_URL={v['BASE_URL']}",
        f"ADMIN_EMAIL={v['ADMIN_EMAIL']}",
        f"HTTP_PORT={v['HTTP_PORT']}",
        f"MQTT_PORT={v['MQTT_PORT']}",
        "",
        "# Database",
        f"DB_NAME={v['DB_NAME']}",
        f"DB_USER={v['DB_USER']}",
        f"DB_PASSWORD={v['DB_PASSWORD']}",
        f"DB_PORT={v['DB_PORT']}",
        "",
        "# Security",
        f"HASH_SECRET={v['HASH_SECRET']}",
        f"JWT_SECRET={v['JWT_SECRET']}",
        f"SECURE_ENROLLMENT={v['SECURE_ENROLLMENT']}",
        "",
        "# MQTT",
        f"MQTT_AUTH={v['MQTT_AUTH']}",
        f"MQTT_MESSAGE_DELAY={v['MQTT_MESSAGE_DELAY']}",
        "",
        "# SMTP (optional)",
        f"SMTP_HOST={v['SMTP_HOST']}",
        f"SMTP_PORT={v['SMTP_PORT']}",
        f"SMTP_SSL={v['SMTP_SSL']}",
        f"SMTP_STARTTLS={v['SMTP_STARTTLS']}",
        f"SMTP_USERNAME={v['SMTP_USERNAME']}",
        f"SMTP_PASSWORD={v['SMTP_PASSWORD']}",
        f"SMTP_FROM={v['SMTP_FROM']}",
        "",
        "# Cloudflare Tunnel (optional)",
        f"CLOUDFLARE_TUNNEL_TOKEN={v['CLOUDFLARE_TUNNEL_TOKEN']}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def read_setup_done() -> dict:
    if not SETUP_STATE_FILE.exists():
        return {}
    try:
        return json.loads(SETUP_STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_setup_done(base_url: str):
    payload = {
        "completed": True,
        "base_url": base_url,
        "timestamp": int(time.time()),
    }
    SETUP_STATE_FILE.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def append_log(line: str):
    with STATE_LOCK:
        STATE["logs"].append(line)
        # Keep memory bounded
        if len(STATE["logs"]) > 1500:
            STATE["logs"] = STATE["logs"][-1000:]


def set_phase(phase: str):
    with STATE_LOCK:
        STATE["phase"] = phase


def set_error(message: str):
    with STATE_LOCK:
        STATE["error"] = message
        STATE["running"] = False


def set_done(base_url: str):
    with STATE_LOCK:
        STATE["done"] = True
        STATE["running"] = False
        STATE["base_url"] = base_url


def docker_available() -> bool:
    try:
        return subprocess.run(["docker", "info"], capture_output=True).returncode == 0
    except FileNotFoundError:
        return False


def run_compose_stream(args, cwd: Path) -> int:
    cmd = ["docker", "compose"] + args
    append_log("$ " + " ".join(cmd))
    try:
        proc = subprocess.Popen(
            cmd,
            cwd=str(cwd),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
    except FileNotFoundError:
        append_log("ERROR: docker command not found")
        return 127

    assert proc.stdout is not None
    for line in proc.stdout:
        append_log(line.rstrip())
    return proc.wait()


def wait_http_local(http_port: str, timeout_sec: int = 180) -> bool:
    url = f"http://localhost:{http_port}/"
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=5) as r:
                if r.status < 500:
                    return True
        except Exception:
            pass
        time.sleep(3)
    return False


def wait_https_public(base_url: str, timeout_sec: int = 240) -> bool:
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(base_url, timeout=8) as r:
                if r.status < 500:
                    return True
        except Exception:
            pass
        time.sleep(5)
    return False


def validate_form(v: dict) -> str:
    required = ["BASE_URL", "ADMIN_EMAIL", "DB_PASSWORD"]
    for key in required:
        if not v.get(key, "").strip():
            return f"{key} is required"

    if not (v["BASE_URL"].startswith("http://") or v["BASE_URL"].startswith("https://")):
        return "BASE_URL must start with http:// or https://"

    for p in ("HTTP_PORT", "MQTT_PORT", "DB_PORT"):
        try:
            n = int(v[p])
            if n < 1 or n > 65535:
                return f"{p} must be between 1 and 65535"
        except ValueError:
            return f"{p} must be a valid integer"

    return ""


def compose_worker(values: dict):
    with STATE_LOCK:
        STATE["running"] = True
        STATE["done"] = False
        STATE["error"] = ""
        STATE["phase"] = "initializing"
        STATE["logs"] = []
        STATE["base_url"] = values["BASE_URL"]
        STATE["http_port"] = values["HTTP_PORT"]

    append_log("Writing hmdm-server/.env...")
    write_env(ENV_FILE, values)
    append_log(f"Saved: {ENV_FILE}")

    if not docker_available():
        set_error("Docker daemon is not running or docker CLI is not installed.")
        append_log("ERROR: Docker is unavailable")
        return

    use_tunnel = bool(values.get("CLOUDFLARE_TUNNEL_TOKEN", "").strip())
    profile_args = ["--profile", "tunnel"] if use_tunnel else []

    set_phase("building")
    append_log("Starting Docker build (Android APK + server)...")
    rc = run_compose_stream(profile_args + ["build"], SERVER_DIR)
    if rc != 0:
        set_error(f"docker compose build failed (exit {rc})")
        return

    set_phase("starting")
    append_log("Starting containers...")
    rc = run_compose_stream(profile_args + ["up", "-d"], SERVER_DIR)
    if rc != 0:
        set_error(f"docker compose up -d failed (exit {rc})")
        return

    set_phase("health-check-local")
    append_log("Waiting for local server health check...")
    if not wait_http_local(values["HTTP_PORT"]):
        set_error("Local server health check failed (localhost not ready in time).")
        append_log("Tip: check logs with `docker logs -f hmdm-server`")
        return

    set_phase("health-check-public")
    append_log(f"Waiting for public URL: {values['BASE_URL']}")
    if not wait_https_public(values["BASE_URL"]):
        set_error(
            "Local server is up, but public URL is not reachable yet. "
            "Check DNS/Cloudflare tunnel/TLS and retry."
        )
        return

    set_phase("completed")
    append_log("Setup complete. Opening admin panel is now safe.")
    write_setup_done(values["BASE_URL"])
    set_done(values["BASE_URL"])


def parse_form_data(body: bytes) -> dict:
    raw = urllib.parse.parse_qs(body.decode("utf-8"), keep_blank_values=True)
    def g(k, d=""):
        return raw.get(k, [d])[0].strip()

    existing = load_env(ENV_FILE)

    values = {
        "BASE_URL": g("BASE_URL", existing.get("BASE_URL", "https://brothers-mdm.com")),
        "ADMIN_EMAIL": g("ADMIN_EMAIL", existing.get("ADMIN_EMAIL", "admin@example.com")),
        "HTTP_PORT": g("HTTP_PORT", existing.get("HTTP_PORT", "8080")),
        "MQTT_PORT": g("MQTT_PORT", existing.get("MQTT_PORT", "31000")),
        "DB_NAME": g("DB_NAME", existing.get("DB_NAME", "hmdm")),
        "DB_USER": g("DB_USER", existing.get("DB_USER", "hmdm")),
        "DB_PASSWORD": g("DB_PASSWORD", existing.get("DB_PASSWORD", "")),
        "DB_PORT": g("DB_PORT", existing.get("DB_PORT", "5432")),
        "HASH_SECRET": g("HASH_SECRET", existing.get("HASH_SECRET", secrets.token_urlsafe(24))),
        "JWT_SECRET": g("JWT_SECRET", existing.get("JWT_SECRET", secrets.token_hex(20))),
        "SECURE_ENROLLMENT": g("SECURE_ENROLLMENT", existing.get("SECURE_ENROLLMENT", "0")),
        "MQTT_AUTH": g("MQTT_AUTH", existing.get("MQTT_AUTH", "1")),
        "MQTT_MESSAGE_DELAY": g("MQTT_MESSAGE_DELAY", existing.get("MQTT_MESSAGE_DELAY", "0")),
        "SMTP_HOST": g("SMTP_HOST", existing.get("SMTP_HOST", "")),
        "SMTP_PORT": g("SMTP_PORT", existing.get("SMTP_PORT", "25")),
        "SMTP_SSL": g("SMTP_SSL", existing.get("SMTP_SSL", "0")),
        "SMTP_STARTTLS": g("SMTP_STARTTLS", existing.get("SMTP_STARTTLS", "0")),
        "SMTP_USERNAME": g("SMTP_USERNAME", existing.get("SMTP_USERNAME", "")),
        "SMTP_PASSWORD": g("SMTP_PASSWORD", existing.get("SMTP_PASSWORD", "")),
        "SMTP_FROM": g("SMTP_FROM", existing.get("SMTP_FROM", "")),
        "CLOUDFLARE_TUNNEL_TOKEN": g("CLOUDFLARE_TUNNEL_TOKEN", existing.get("CLOUDFLARE_TUNNEL_TOKEN", "")),
    }
    return values


def render_page() -> str:
    existing = load_env(ENV_FILE)
    done = read_setup_done()

    base_url = html.escape(existing.get("BASE_URL", "https://brothers-mdm.com"))
    admin_email = html.escape(existing.get("ADMIN_EMAIL", "admin@example.com"))

    if done.get("completed"):
        done_url = html.escape(done.get("base_url", existing.get("BASE_URL", "https://brothers-mdm.com")))
        return f"""<!doctype html>
<html>
<head>
<meta charset=\"utf-8\" />
<title>Brother Pharmach MDM - Setup Complete</title>
<style>
body {{ font-family: sans-serif; max-width: 760px; margin: 2rem auto; padding: 0 1rem; }}
.card {{ border: 1px solid #ddd; border-radius: 8px; padding: 1rem; }}
.btn {{ display: inline-block; padding: .7rem 1rem; border: 1px solid #333; border-radius: 6px; text-decoration: none; }}
.small {{ color: #666; font-size: 0.9rem; }}
</style>
</head>
<body>
<h2>Setup already completed</h2>
<div class=\"card\">
<p>This setup is one-time only and has already been completed.</p>
<p><a class=\"btn\" href=\"{done_url}\" target=\"_blank\" rel=\"noopener\">Continue to Admin Panel</a></p>
<p class=\"small\">To rerun setup manually, delete: {SETUP_STATE_FILE}</p>
</div>
</body>
</html>"""

    def val(name: str, default: str) -> str:
        return html.escape(existing.get(name, default))

    return f"""<!doctype html>
<html>
<head>
<meta charset=\"utf-8\" />
<title>Brother Pharmach MDM - First Setup</title>
<style>
body {{ font-family: sans-serif; max-width: 900px; margin: 1rem auto; padding: 0 1rem; }}
.grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 10px 14px; }}
label {{ display:block; font-size: .92rem; color: #333; margin-bottom: 3px; }}
input {{ width: 100%; padding: .5rem; box-sizing: border-box; }}
fieldset {{ border: 1px solid #ddd; border-radius: 8px; margin: 12px 0; }}
legend {{ padding: 0 6px; font-weight: 600; }}
button {{ padding: .7rem 1.2rem; }}
#logs {{ background:#111; color:#ddd; padding:.8rem; border-radius:8px; height:260px; overflow:auto; white-space:pre-wrap; }}
#status {{ margin: .7rem 0; font-weight: 600; }}
#doneBtn {{ display:none; margin-top:10px; }}
.note {{ color:#555; font-size:.9rem; }}
</style>
</head>
<body>
<h2>Brother Pharmach MDM - First-time Setup</h2>
<p class=\"note\">Fill values once, submit, and wait for health checks. QR will use your own APK URL only.</p>

<form id=\"setupForm\">
<fieldset><legend>Server</legend>
<div class=\"grid\">
<div><label>BASE_URL *</label><input name=\"BASE_URL\" value=\"{base_url}\" required /></div>
<div><label>ADMIN_EMAIL *</label><input name=\"ADMIN_EMAIL\" value=\"{admin_email}\" required /></div>
<div><label>HTTP_PORT</label><input name=\"HTTP_PORT\" value=\"{val('HTTP_PORT','8080')}\" /></div>
<div><label>MQTT_PORT</label><input name=\"MQTT_PORT\" value=\"{val('MQTT_PORT','31000')}\" /></div>
</div>
</fieldset>

<fieldset><legend>Database</legend>
<div class=\"grid\">
<div><label>DB_NAME</label><input name=\"DB_NAME\" value=\"{val('DB_NAME','hmdm')}\" /></div>
<div><label>DB_USER</label><input name=\"DB_USER\" value=\"{val('DB_USER','hmdm')}\" /></div>
<div><label>DB_PASSWORD *</label><input type=\"password\" name=\"DB_PASSWORD\" value=\"{val('DB_PASSWORD','')}\" required /></div>
<div><label>DB_PORT</label><input name=\"DB_PORT\" value=\"{val('DB_PORT','5432')}\" /></div>
</div>
</fieldset>

<fieldset><legend>Security</legend>
<div class=\"grid\">
<div><label>HASH_SECRET</label><input name=\"HASH_SECRET\" value=\"{val('HASH_SECRET', secrets.token_urlsafe(24))}\" /></div>
<div><label>JWT_SECRET</label><input name=\"JWT_SECRET\" value=\"{val('JWT_SECRET', secrets.token_hex(20))}\" /></div>
<div><label>SECURE_ENROLLMENT (0/1)</label><input name=\"SECURE_ENROLLMENT\" value=\"{val('SECURE_ENROLLMENT','0')}\" /></div>
</div>
</fieldset>

<fieldset><legend>MQTT + SMTP + Tunnel</legend>
<div class=\"grid\">
<div><label>MQTT_AUTH</label><input name=\"MQTT_AUTH\" value=\"{val('MQTT_AUTH','1')}\" /></div>
<div><label>MQTT_MESSAGE_DELAY</label><input name=\"MQTT_MESSAGE_DELAY\" value=\"{val('MQTT_MESSAGE_DELAY','0')}\" /></div>
<div><label>SMTP_HOST</label><input name=\"SMTP_HOST\" value=\"{val('SMTP_HOST','')}\" /></div>
<div><label>SMTP_PORT</label><input name=\"SMTP_PORT\" value=\"{val('SMTP_PORT','25')}\" /></div>
<div><label>SMTP_SSL (0/1)</label><input name=\"SMTP_SSL\" value=\"{val('SMTP_SSL','0')}\" /></div>
<div><label>SMTP_STARTTLS (0/1)</label><input name=\"SMTP_STARTTLS\" value=\"{val('SMTP_STARTTLS','0')}\" /></div>
<div><label>SMTP_USERNAME</label><input name=\"SMTP_USERNAME\" value=\"{val('SMTP_USERNAME','')}\" /></div>
<div><label>SMTP_PASSWORD</label><input type=\"password\" name=\"SMTP_PASSWORD\" value=\"{val('SMTP_PASSWORD','')}\" /></div>
<div><label>SMTP_FROM</label><input name=\"SMTP_FROM\" value=\"{val('SMTP_FROM','')}\" /></div>
<div><label>CLOUDFLARE_TUNNEL_TOKEN (optional)</label><input name=\"CLOUDFLARE_TUNNEL_TOKEN\" value=\"{val('CLOUDFLARE_TUNNEL_TOKEN','')}\" /></div>
</div>
</fieldset>

<button type=\"submit\" id=\"submitBtn\">Start Setup</button>
</form>

<div id=\"status\">Status: idle</div>
<div id=\"logs\"></div>
<a id=\"doneBtn\" href=\"#\" target=\"_blank\" rel=\"noopener\"><button>Continue to Admin Panel</button></a>

<script>
const form = document.getElementById('setupForm');
const logsEl = document.getElementById('logs');
const statusEl = document.getElementById('status');
const doneBtn = document.getElementById('doneBtn');
const submitBtn = document.getElementById('submitBtn');

form.addEventListener('submit', async (e) => {{
  e.preventDefault();
  submitBtn.disabled = true;
  doneBtn.style.display = 'none';
  logsEl.textContent = '';

  const fd = new FormData(form);
  const resp = await fetch('/start', {{ method: 'POST', body: new URLSearchParams(fd) }});
  const data = await resp.json();
  if (!data.ok) {{
    alert(data.error || 'Failed to start setup');
    submitBtn.disabled = false;
    return;
  }}

  pollStatus();
}});

async function pollStatus() {{
  const timer = setInterval(async () => {{
    const resp = await fetch('/status');
    const data = await resp.json();
    statusEl.textContent = 'Status: ' + data.phase + (data.error ? ' | ERROR: ' + data.error : '');
    logsEl.textContent = data.logs.join('\n');
    logsEl.scrollTop = logsEl.scrollHeight;

    if (data.done) {{
      clearInterval(timer);
      doneBtn.href = data.base_url;
      doneBtn.style.display = 'inline-block';
      submitBtn.disabled = true;
      statusEl.textContent = 'Status: completed';
    }}

    if (!data.running && data.error) {{
      clearInterval(timer);
      submitBtn.disabled = false;
    }}
  }}, 2000);
}}
</script>
</body>
</html>"""


class SetupHandler(BaseHTTPRequestHandler):
    def _send_json(self, payload: dict, code: int = 200):
        raw = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def _send_html(self, body: str, code: int = 200):
        raw = body.encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, fmt, *args):
        # Keep terminal clean; progress is shown in web UI.
        return

    def do_GET(self):
        if self.path == "/":
            self._send_html(render_page())
            return

        if self.path == "/status":
            with STATE_LOCK:
                payload = {
                    "running": STATE["running"],
                    "done": STATE["done"],
                    "error": STATE["error"],
                    "phase": STATE["phase"],
                    "logs": STATE["logs"],
                    "base_url": STATE["base_url"],
                }
            self._send_json(payload)
            return

        self._send_json({"ok": False, "error": "Not found"}, code=404)

    def do_POST(self):
        if self.path != "/start":
            self._send_json({"ok": False, "error": "Not found"}, code=404)
            return

        done = read_setup_done()
        if done.get("completed"):
            self._send_json({"ok": False, "error": "Setup already completed (once-only)."}, code=409)
            return

        with STATE_LOCK:
            if STATE["running"]:
                self._send_json({"ok": False, "error": "Setup is already running."}, code=409)
                return

        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length)
        values = parse_form_data(body)
        err = validate_form(values)
        if err:
            self._send_json({"ok": False, "error": err}, code=400)
            return

        t = threading.Thread(target=compose_worker, args=(values,), daemon=True)
        t.start()
        self._send_json({"ok": True})


def can_bind(host: str, port: int) -> bool:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.bind((host, port))
    except OSError:
        return False
    finally:
        s.close()
    return True


def main():
    if not SERVER_DIR.exists():
        print(f"ERROR: Missing directory: {SERVER_DIR}")
        sys.exit(1)

    if not can_bind(HOST, PORT):
        print(f"ERROR: Port {PORT} is already in use. Stop the other process and retry.")
        sys.exit(1)

    url = f"http://{HOST}:{PORT}/"
    print(f"Starting setup web UI at: {url}")
    print("Opening browser...")

    # Best-effort browser launch
    try:
        webbrowser.open(url, new=2, autoraise=True)
    except Exception:
        pass

    server = ThreadingHTTPServer((HOST, PORT), SetupHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nSetup server stopped.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
